title: FirstName LastName
#logo: /assets/img/headshot_circle.png
#description: text below image
#show_downloads: true
theme: jekyll_theme_minima

# Foreign Affairs Council

### About Me 
Hello! I am an experienced Global Studies student and aspiring foreign affairs council professional with over 3 years of proven expertise in foreign affairs and conflict, justice, and human rights. 

With skills in organizing data, graphing and interpreting data, coding, and virtual presentations, I am able to execute sorting data efficiently, and achieve easily accessible and readable data. I am adept at using Excel, SPSS, and Python. 

My complex skill set, commitment to organization, and passion for foreign affairs makes me as a valuable asset.  In my spare time, I like to play ice hockey and read. 

You can find me on [LinkedIn](www.linkedin.com/in/keira-rosario-5489612b7).


### Education 
BA in Global Studies
Loyola University, MD

### Projects

#### Budget Tracker
 - image
 - Report

***
#### Personality Test
 - image
 - write up

***
#### Cricket Chirps Data
 - image
 - write up
