title: "Keira Rosario"
# logo: /assets/img/headshot_circle.png
# description: Keira Rosario
# show_downloads: true
theme: jekyll-theme-minima

description: |
  ### About Me

  ### Education 
 
  ### Projects

  #### Budget Tracker
 
  #### Personality Test

  #### Cricket Chirps Data
   


