title: FirstName LastName
#logo: /assets/img/headshot_circle.png
#description: text below image
#show_downloads: true
theme: jekyll_theme_minima

about_me:

# Foreign Affairs Council

### About Me 
Hello! I am an experienced Global Studies student and aspiring foreign affairs council professional with over 3 years of proven expertise in foreign affairs and conflict, justice, and human rights. 

With skills in organizing data, graphing and interpreting data, coding, and virtual presentations, I am able to execute sorting data efficiently, and achieve easily accessible and readable data. I am adept at using Excel, SPSS, and Python. 

My complex skill set, commitment to organization, and passion for foreign affairs makes me as a valuable asset.  In my spare time, I like to play ice hockey and read. 

You can find me on [LinkedIn](www.linkedin.com/in/keira-rosario-5489612b7).


### Education 
BA in Global Studies
Loyola University, MD

### Projects

#### Budget Tracker
 - image

I created my budget tracker to organize my biweekly income with the goal of saving an optimal amount of money each check. Having a large savings is important for my upcoming trip abroad to Copenhagen. This was important for me to sort out so I’m in an ideal financial situation for the four months I’m unable to work. 


In this project, I demonstrated my skills with excel. Specifically, the use of formulas, organization, and use of conditional formatting. 


During this project, I faced the issue of perfecting my formulas because Excel is very specific with what will work, whether its parenthesis, order, and/or symbols. Checking my work multiple times helped me overcome this as well as the ability to apply formulas to an entire row using the $ symbol. 
 

In this project, I collaborated with Judy and Chase. We shared what formatting worked and didn’t work as well as checking each other’s work for errors we may have missed while reviewing ourselves. 


I went into this project hoping to create a budget I can follow to maximize my savings without preventing me from also enjoying my money which I was able to achieve. If I could take this project further, I would add an additional section to organize my savings for varies reasons. 


***
#### Personality Test
 - image

I came up with the personality quiz project to create a series of questions that would answer which type of flower you are. Although this is not specifically a problem that needs to be solved, it can be altered to gather data for other purposes. 


In this project, I used python and numerous codes to complete various functions. Outside of the program, I used problem solving and collaboration when I was unsuccessful with my coding. 


I faced the issue of having small errors in my code that prevented it to run completely through. I found that copying and pasting my code into a Word Document and using the command F function helped for me to find errors. 


I collaborated with Chase, Judy, and Cortez through checking each other’s work and sharing resources such as YouTube videos to help out along the way. 


My initial goal was to create a survey of questions that answered which type of flower one’s personality matched the most. I was able to achieve this but in the future I would likely use this to conduct surveys on other topics. 


***
#### Cricket Chirps Data
 - image


This project involved organizing data surrounding the relationship between cricket chirps per 15 seconds with the temperature and time of day. This showed the relationship was stronger between the chirping with the temperature which can allow us to figure out when crickets are the most active.  

In this project I used SPSS and numerous functions, graphing, and data analyzing. 


In this project, I struggled to find where the equation the graph was showing was in SPSS. I did some research and figured out where in this program I could find the equation to make my own for other numbers.  


I did not collaborate with anyone on this project, but I did use online sources that helped explain how to use SPSS.  


I set out to find which relation was stronger with cricket chirps and found that temperature had the greatest relation. If I took this project further, I would use multiple sets of data to compare to see if the relation continues in other recordings. 

